### ISSUE TITLE
How I restart browser between Scenarios?

### ISSUE THREAD

**Issue by sanko1983** [igniteram/protractor-cucumber-typescript#40]
Hi @igniteram ,

Im trying run every scenario with a new browser but doesnt work.

I have added inside of hooks.js :

After(async function(scenario) {
    if (scenario.result.status === Status.FAILED) {
        // screenShot is a base-64 encoded PNG
         const screenShot = await browser.takeScreenshot();
         this.attach(screenShot, "image/png");
    }
    **await browser.restart(); // <-- Added restart browser**
});

Any idea?

Regards!

**Comment by igniteram** [comment]
@sanko1983 What error/exception are you facing ? can you paste the stacktrace ? Also the protractror and cucumber version you are using! Always put these information first as it would be easy to debug

**Comment by sanko1983** [comment]
Hi @igniteram , very true, sorry.

**On my package.json :** 

"devDependencies": {
    "@types/cucumber": "^2.0.4",
    "@types/node": "^8.0.3",
    "@types/selenium-webdriver": "^3.0.7",
    "chai": "^4.0.2",
    "chai-as-promised": "^7.0.0",
    "cucumber": "^3.0.4",
    "cucumber-html-reporter": "^3.0.4",
    "mkdirp": "^0.5.1",
    "protractor": "^5.1.2",
    "protractor-cucumber-framework": "^4.0.8",
    "rimraf": "^2.6.2",
    "ts-node": "^3.3.0",
    "typescript": "^2.5.3"
  },


**I have added inside of hooks.js :**

After(async function(scenario) {
if (scenario.result.status === Status.FAILED) {
// screenShot is a base-64 encoded PNG
const screenShot = await browser.takeScreenshot();
this.attach(screenShot, "image/png");
}
await browser.restart(); // <-- Added restart browser
});

**log:** 

PS D:\path\protractor-cucumber-typescript> npm test

> protractor-typescript-cucumber@3.0.0 test D:\path\protractor-cucumber-typescript
> protractor typeScript/config/config.js

(node:11944) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[15:17:56] I/launcher - Running 1 instances of WebDriver
[15:17:56] I/hosted - Using the selenium server at http://127.0.0.1:4444/wd/hub
.....F-..F-.

Failures:

1) Scenario: Cucumber Google Search1 # features\cucumber.feature:10
   √ Given I am on amazon page # stepdefinitions\homePage.ts:9
   × When I type "cucumber" # stepdefinitions\homePage.ts:13
       NoSuchSessionError: This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.
           at session_.flow_.promise (D:\path\protractor-cucumber-typescript\node_modules\selenium-webdriver\lib\webdriver.js:847:16)
           at new Promise (<anonymous>)
           at SimpleScheduler.promise (D:\path\protractor-cucumber-typescript\node_modules\selenium-webdriver\lib\promise.js:2242:12)
           at promise.finally (D:\path\protractor-cucumber-typescript\node_modules\selenium-webdriver\lib\webdriver.js:846:34)
           at promise.then.error (D:\path\protractor-cucumber-typescript\node_modules\selenium-webdriver\lib\promise.js:1684:12)
           at <anonymous>
           at process._tickCallback (internal/process/next_tick.js:188:7)Error
           at ElementArrayFinder.applyAction_ (D:\path\protractor-cucumber-typescript\node_modules\protractor\built\element.js:459:27)
           at ElementArrayFinder.(anonymous function).args [as sendKeys] (D:\path\protractor-cucumber-typescript\node_modules\protractor\built\element.js:91:29)
           at ElementFinder.(anonymous function).args [as sendKeys] (D:\path\protractor-cucumber-typescript\node_modules\protractor\built\element.js:831:22)
           at Object.<anonymous> (D:\path\protractor-cucumber-typescript\stepdefinitions\homePage.ts:14:32)
           at Generator.next (<anonymous>)
           at D:\path\protractor-cucumber-typescript\stepdefinitions\homePage.ts:7:71
           at new Promise (<anonymous>)
           at __awaiter (D:\path\protractor-cucumber-typescript\stepdefinitions\homePage.ts:3:12)
           at World.When (D:\path\protractor-cucumber-typescript\stepdefinitions\homePage.ts:13:41)Error
           at ElementArrayFinder.applyAction_ (D:\path\protractor-cucumber-typescript\node_modules\protractor\built\element.js:459:27)
           at ElementArrayFinder.(anonymous function).args [as sendKeys] (D:\path\protractor-cucumber-typescript\node_modules\protractor\built\element.js:91:29)
           at ElementFinder.(anonymous function).args [as sendKeys] (D:\path\protractor-cucumber-typescript\node_modules\protractor\built\element.js:831:22)
           at Object.<anonymous> (D:\path\protractor-cucumber-typescript\stepdefinitions\homePage.ts:14:32)
           at Generator.next (<anonymous>)
           at D:\path\protractor-cucumber-typescript\stepdefinitions\homePage.ts:7:71
           at new Promise (<anonymous>)
           at __awaiter (D:\path\protractor-cucumber-typescript\stepdefinitions\homePage.ts:3:12)
           at World.When (D:\path\protractor-cucumber-typescript\stepdefinitions\homePage.ts:13:41)
   - When I click on search button # stepdefinitions\homePage.ts:17
   √ After # support\hooks.ts:13

2) Scenario: Cucumber Google Search2 # features\cucumber.feature:16
   √ Given I am on amazon page # stepdefinitions\homePage.ts:9
   × When I type "cucumber" # stepdefinitions\homePage.ts:13
       NoSuchSessionError: This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.
           at session_.flow_.promise (D:\path\protractor-cucumber-typescript\node_modules\selenium-webdriver\lib\webdriver.js:847:16)
           at new Promise (<anonymous>)
           at SimpleScheduler.promise (D:\path\protractor-cucumber-typescript\node_modules\selenium-webdriver\lib\promise.js:2242:12)
           at promise.finally (D:\path\protractor-cucumber-typescript\node_modules\selenium-webdriver\lib\webdriver.js:846:34)
           at promise.then.error (D:\path\protractor-cucumber-typescript\node_modules\selenium-webdriver\lib\promise.js:1684:12)
           at <anonymous>
           at process._tickCallback (internal/process/next_tick.js:188:7)Error
           at ElementArrayFinder.applyAction_ (D:\path\protractor-cucumber-typescript\node_modules\protractor\built\element.js:459:27)
           at ElementArrayFinder.(anonymous function).args [as sendKeys] (D:\path\protractor-cucumber-typescript\node_modules\protractor\built\element.js:91:29)
           at ElementFinder.(anonymous function).args [as sendKeys] (D:\path\protractor-cucumber-typescript\node_modules\protractor\built\element.js:831:22)
           at Object.<anonymous> (D:\path\protractor-cucumber-typescript\stepdefinitions\homePage.ts:14:32)
           at Generator.next (<anonymous>)
           at D:\path\protractor-cucumber-typescript\stepdefinitions\homePage.ts:7:71
           at new Promise (<anonymous>)
           at __awaiter (D:\path\protractor-cucumber-typescript\stepdefinitions\homePage.ts:3:12)
           at World.When (D:\path\protractor-cucumber-typescript\stepdefinitions\homePage.ts:13:41)Error
           at ElementArrayFinder.applyAction_ (D:\Profiles\aiglesiasexposito\Documents\GitHub\protractor-cucumber-typescript\node_modules\protractor\built\element.js:459:27)
           at ElementArrayFinder.(anonymous function).args [as sendKeys] (D:\path\protractor-cucumber-typescript\node_modules\protractor\built\element.js:91:29)
           at ElementFinder.(anonymous function).args [as sendKeys] (D:\path\protractor-cucumber-typescript\node_modules\protractor\built\element.js:831:22)
           at Object.<anonymous> (D:\path\protractor-cucumber-typescript\stepdefinitions\homePage.ts:14:32)
           at Generator.next (<anonymous>)
           at D:\path\protractor-cucumber-typescript\stepdefinitions\homePage.ts:7:71
           at new Promise (<anonymous>)
           at __awaiter (D:\path\protractor-cucumber-typescript\stepdefinitions\homePage.ts:3:12)
           at World.When (D:\path\protractor-cucumber-typescript\stepdefinitions\homePage.ts:13:41)
   - When I click on search button # stepdefinitions\homePage.ts:17
   √ After # support\hooks.ts:13

3 scenarios (2 failed, 1 passed)
9 steps (2 failed, 2 skipped, 5 passed)
0m08.250s
Cucumber HTML report D:\path\protractor-cucumber-typescript\reports\html/cucumber_reporter.html generated successfully.
[15:18:33] I/launcher - 0 instance(s) of WebDriver still running
[15:18:33] I/launcher - chrome #01 failed 2 test(s)
[15:18:33] I/launcher - overall: 2 failed spec(s)
[15:18:33] E/launcher - Process exited with error code 1
npm ERR! Test failed.  See above for more details.

More info : it's your project, only I have changed the cucumber steps.

Regards!

**Comment by igniteram** [comment]
@sanko1983 Sorry for the late reply, I have been travelling a lo lately. Are you still facing this issue? And also did switch one the `restartBrowserBetweenTests` flag in the config file? please refer this config interface - https://github.com/angular/protractor/blob/master/lib/config.ts#L531. let me know!

**Comment by igniteram** [comment]
Closing this issue due to inactivity , please feel free to raise a new one if the issue still exists!

**Comment by Phonesis** [comment]
any news on this? There does seem to be a bug with setting protractor to not re-use browser between scenarios. Also, browser.restart doesn't seem to do anything.

**Comment by Amrishs94** [comment]
close the browser each time after executing a scenario and launching the url again on running the next scenario

**Comment by igniteram** [comment]
@Phonesis @Amrishs94 will continue the discussion in the new issue #63
